
import { getSession } from "next-auth/client";
import Head from 'next/head';
import Header from '../components/Header/Header';
import Login from '../components/Login/Login';

export default function Home({ session }) {
  //if user is not login so return login component
  if (!session) return <Login />
  // if user is already login so otherise return entire app
  return (
    <div>
      <Head>
        <title>Facebook Web App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Header />
    </div>
  );
}


export async function getServerSideProps(context) {
  //get the user
  const session = await getSession(context);
   
  return {
    props: {
      session
    }
  }
}
