
import { getSession } from "next-auth/client";
import Head from 'next/head';
import Feed from "../components/Feed/Feed";
import Header from '../components/Header/Header';
import Login from '../components/Login/Login';
import Sidebar from "../components/Sidebar/Sidebar";

export default function Home({ session }) {
  //if user is not login so return login component
  if (!session) return <Login />
  // if user is already login so otherise return entire app
  return (
    <div className="h-screen bg-gray-100 overflow-hidden">
      <Head>
        <title>Facebook Web App</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      
     <Header />
     <main className="flex">
      <Sidebar />
      <Feed />
     </main>

    </div>
  );
}


export async function getServerSideProps(context) {
  //get the user
  const session = await getSession(context);
   
  return {
    props: {
      session
    }
  }
}
